# Generated by Django 2.1.15 on 2023-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='teacherextra',
            name='salary',
        ),
    ]
